# Generated by Django 4.1.4 on 2022-12-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='leaves',
        ),
        migrations.AlterField(
            model_name='branch',
            name='leaf_parent',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='Trees.branch'),
        ),
    ]
