# Generated by Django 4.1.4 on 2022-12-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0002_remove_branch_leaves_alter_branch_leaf_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='leaf_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='Trees.branch'),
        ),
    ]
