# Generated by Django 4.1.4 on 2022-12-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0003_alter_branch_leaf_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='leaves_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='unsolved',
            field=models.IntegerField(default=0),
        ),
    ]
