# Generated by Django 4.1.4 on 2022-12-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0004_branch_leaves_count_branch_unsolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='focused',
            field=models.BooleanField(default=False),
        ),
    ]
