# Generated by Django 4.1.4 on 2022-12-24 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0005_branch_focused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='leaf',
        ),
        migrations.AddField(
            model_name='comment',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='Trees.branch'),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='comments',
        ),
        migrations.AddField(
            model_name='branch',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
