# Generated by Django 4.1.4 on 2022-12-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0006_remove_comment_leaf_comment_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='thumbnail_url',
            field=models.TextField(default=''),
        ),
    ]
