# Generated by Django 4.1.4 on 2022-12-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0007_branch_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_issue',
            field=models.BooleanField(default=True),
        ),
    ]
