# Generated by Django 4.1.4 on 2022-12-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0009_tag_remove_branch_tags_branch_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_issue',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='issue_solved',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='comment',
            name='state',
            field=models.TextField(default='Do'),
        ),
    ]
