# Generated by Django 4.1.4 on 2022-12-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0011_comment_date_alter_comment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='studied_options',
            field=models.TextField(default=''),
        ),
    ]
