# Generated by Django 4.1.4 on 2022-12-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0012_branch_studied_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
