# Generated by Django 4.1.4 on 2023-01-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0013_branch_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='sub_categories',
            field=models.TextField(default=''),
        ),
    ]
