# Generated by Django 4.1.4 on 2023-01-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0016_comment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.TextField(default=''),
        ),
    ]
