# Generated by Django 4.1.4 on 2023-01-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0018_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
    ]
