# Generated by Django 4.1.4 on 2023-01-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0019_branch_image_height_branch_image_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='sub_categories',
        ),
    ]
