# Generated by Django 4.1.4 on 2023-01-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0020_remove_tag_category_remove_tag_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='focused',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
