# Generated by Django 4.1.4 on 2023-01-03 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0021_alter_branch_focused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='reference_origin',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trees.branch'),
        ),
    ]
