# Generated by Django 4.1.4 on 2023-01-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0022_alter_branch_reference_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='reference_origin',
        ),
        migrations.AddField(
            model_name='branch',
            name='reference_origin',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='Trees.branch'),
        ),
    ]
