# Generated by Django 4.1.4 on 2023-01-03 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0023_remove_branch_reference_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='reference_origin',
        ),
        migrations.AddField(
            model_name='branch',
            name='reference_origin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trees.branch'),
        ),
    ]
