# Generated by Django 4.1.4 on 2023-01-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trees', '0024_remove_branch_reference_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dismissed',
            field=models.IntegerField(default=0),
        ),
    ]
