# Generated by Django 4.1.4 on 2023-01-04 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trees', '0025_comment_dismissed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
